language: python
sudo: false
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=flake8
addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - lmodern
install:
  # Stolen from https://github.com/yihui/knitr/blob/master/.travis.yml
  - "[ ! -d ~/bin ] && mkdir ~/bin || true"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - travis_retry pip install tox

cache:
  directories:
  - $HOME/bin

script:
  - pandoc -v
  - tox
