language: python
sudo: false
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=flake8
addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - lmodern
install:
  - travis_retry pip install tox
  # download a newer pandoc version...
  - python setup.py download_pandoc

script:
  - pandoc -v
  - python -c "import pypandoc; print(pypandoc.get_pandoc_path(), pypandoc.get_pandoc_version())"
  - tox
